name: "Release"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]
  pull_request:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

concurrency:
  group: "${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          config-file: "release-please-config.json"
          manifest-file: ".release-please-manifest.json"
          release-type: bazel

      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  artifacts:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.created && !failure() }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download Release artifacts
        uses: actions/download-artifact@v4
        with:
          name: distributables
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{github.event.client_payload.run_id }}

      - name: Upload artifacts to Release-Please GitHub release
        run: |
          gh release upload ${{ needs.release.outputs.tag }} dist/*.tar.gz dist/*.txt
