name: "Release"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]
  pull_request:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

concurrency:
  group: "${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Auto-merge Release-Please PR
        run: |
          gh pr merge ${{ github.event.client_payload.pr_number }} --squash

      - name: Run Release-Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          config-file: "release-please-config.json"
          manifest-file: ".release-please-manifest.json"
          release-type: bazel

  artifacts:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.created && !failure() }}
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Download Release artifacts
        uses: actions/download-artifact@v4
        with:
          name: distributables
          path: dist
          github-token: ${{ env.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.client_payload.run_id }}

      - name: Build final SHA256 checksums
        run: |
          scripts/release.sh checksums

      - name: Upload artifacts to Release-Please GitHub release
        run: |
          gh release upload ${{ needs.release.outputs.tag }} dist/*.tar.gz dist/CHECKSUMS.txt
