name: "Run Super-Linter"

on: ["push", "pull_request"]

permissions: read-all

jobs:
  lint:
    name: Super-Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Run Prettier
        run: |
          pnpm dlx prettier --write "**/*.md"

      - name: Commit Prettier changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(docs): format documentation with Prettier"
          branch: ${{ github.head_ref }}

      - name: Superlinter
        uses: super-linter/super-linter@v7.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (.*.mod|.*.sum)
          BASH_EXEC_IGNORE_LIBRARIES: true
          # mostly false positives
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_JSCPD: false
          VALIDATE_KUBERNETES_KUBECONFORM: false
          # there individual Go files to be linted (all modules)
          VALIDATE_GO: false
          # disable for now, as it's a bit too early for strict rules
          VALIDATE_GO_MODULES: false
